# Generated by Django 2.2.5 on 2019-09-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short', models.TextField()),
                ('url', models.TextField()),
                ('clicks', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
